version: '3'
services:



  pomodoro-pgsql:
    image: postgres:alpine
    # image: pomodoro-pgsql
    volumes:
      - basicservice-pgsql-volume:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Password1
      - POSTGRES_USER=samplesam
      - POSTGRES_DB=defaultdb
      - PGDATA=/var/lib/postgresql/data/pgdata

# TODO: Change image to local image


  basicservice-api:
    # image: basicservice-api
    image: basicservice.api-api-service
    extra_hosts:
      - localmachine:172.31.1.1
    volumes:
      - ${PLATFORM_REPOS}/BasicService.API/BasicService.Api/src/:/app/src/
      - ${PLATFORM_REPOS}/BasicService.API/BasicService.Api/wwwroot/:/app/wwwroot/
      - ${PLATFORM_REPOS}/BasicService.API/BasicService.Api/secrets/:/app/secrets/
      - ${PLATFORM_REPOS}/BasicService.API/BasicService.Api/Migrations/:/app/Migrations/
      - ${PLATFORM_REPOS}/BasicService.API/BasicService.Api/configMounts/compose/:/app/config/      
    entrypoint: dotnet ef database update

volumes:
  basicservice-pgsql-volume:  

## Move network to 'platform' project
## TODO Add external link

networks:
  default:
    external:
        name: pomodoro-net
