version: '3'
services:

# TODO: Change image to local image

  watch-pomo-rapi:
    image: basicservice-watch-rapi
    # networks:
    #   - external:
    #       name: basicservice-net
      # - basicservice-net
    extra_hosts:
      - localmachine:172.31.1.1
    volumes:
      - ${POMODORO_REPOS}/PersonalTracker.Api/BasicService/BasicService.Api/src/:/app/src/
      - ${POMODORO_REPOS}/PersonalTracker.Api/BasicService/BasicService.Api/wwwroot/:/app/wwwroot/
      - ${POMODORO_REPOS}/PersonalTracker.Api/BasicService/BasicService.Api/secrets/:/app/secrets/
      - ${POMODORO_REPOS}/PersonalTracker.Api/BasicService/BasicService.Api/Migrations/:/app/Migrations/
      # - ${POMODORO_REPOS}/PersonalTracker.Api/Mountebank/api_conf/:/app/config/
    entrypoint: dotnet ef database update

# volumes:
#   basicservice-pgsql-volume:  

## Move network to 'platform' project
## TODO Add external link

networks:
  default:
    external:
        name: basicservice-net
