version: '3'
services:

## TODO: Move database to 'platform' project

  pomodoro-pgsql:
    # image: pomodoro-pgsql
    image: postgres:alpine
    volumes:
      - basicservice-pgsql-volume:/var/lib/postgresql/data/pgdata
    networks:
      - pomodoro-net
    extra_hosts:
      - localmachine:172.31.1.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Password1
      - POSTGRES_USER=samplesam
      - POSTGRES_DB=defaultdb
      - PGDATA=/var/lib/postgresql/data/pgdata


  basicservice-api:
    build: ../BasicService.Api
    # image: basicservice-api
    image: basicservice.api-api-service
    entrypoint:
    # - ls
    # - /app/src
    - dotnet
    - watch
    - run
    networks:
      - pomodoro-net
    extra_hosts:
      - localmachine:172.31.1.1
    ports:
      - 2003:8003
    volumes:
      - ${PLATFORM_REPOS}/BasicService.API/BasicService.Api/src/:/app/src/
      - ${PLATFORM_REPOS}/BasicService.API/BasicService.Api/wwwroot/:/app/wwwroot/
      - ${PLATFORM_REPOS}/BasicService.API/BasicService.Api/secrets/:/app/secrets/
      - ${PLATFORM_REPOS}/BasicService.API/BasicService.Api/configMounts/compose/:/app/config/


  # basicservice-api:
  #   image: basicservice-api
  #   networks:
  #     - pomodoro-net
  #   extra_hosts:
  #     - localmachine:172.31.1.1
  #   ports:
  #     - 2003:8003
  #   volumes:
  #     - ${PLATFORM_REPOS}/BasicService.API/BasicService.Api/src/:/app/src/
  #     - ${PLATFORM_REPOS}/BasicService.API/BasicService.Api/wwwroot/:/app/wwwroot/
  #     - ${PLATFORM_REPOS}/BasicService.API/BasicService.Api/secrets/:/app/secrets/

## TODO: Move idserver to 'platform' project

  # pomodoro-idserver:
  #   image: pomodoro-idserver
  #   networks:
  #     - pomodoro-net
  #   extra_hosts:
  #     - localmachine:172.31.1.1
  #   ports:
  #     - 2002:80
  #   volumes:
  #     - ${POMODORO_REPOS}/PersonalTracker.Api/IdServer/src/:/app/src/
  #     - ${POMODORO_REPOS}/PersonalTracker.Api/IdServer/secrets/:/app/secrets/
  #     - ${POMODORO_REPOS}/PersonalTracker.Api/IdServer/config/:/app/config/
  #   # entrypoint: dotnet ef database update
  #   # command: ["--debug"]
    
## TODO: Customize reverse proxy for this service

  # router-reverse-proxy:
  #   image: envoyproxy/envoy:latest
  #   networks:
  #     - pomodoro-net
  #   extra_hosts:
  #     - localmachine:172.31.1.1
  #   ports:
  #     - 80:2081
  #   volumes:
  #     - ${POMODORO_REPOS}/PersonalTracker.Api/envoyproxy/:/etc/envoy/

## TODO: Move utils to 'platform' project

  # utils:
  #   image: pomodoro-utils
  #   networks:
  #     - pomodoro-net
  #   extra_hosts:
  #     - localmachine:172.31.1.1
  #   entrypoint: /bin/sleep 5h


volumes:
  basicservice-pgsql-volume:  

networks:
  pomodoro-net:
    external:
        name: pomodoro-net

